In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('hotel_booking.csv')
df.drop(['name', 'email', 'phone-number', 'credit_card'], axis = 1, inplace = True)
df.drop('company', axis = 1, inplace = True)
df.dropna(inplace = True)
df.reset_index(inplace = True)
df.drop('index', axis = 1, inplace = True)
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
1,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
2,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
3,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,0,No Deposit,303.0,0,Transient,103.00,0,1,Check-Out,2015-07-03
4,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,0,No Deposit,240.0,0,Transient,82.00,0,1,Canceled,2015-05-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102889,City Hotel,0,23,2017,August,35,30,2,5,2,...,0,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06
102890,City Hotel,0,102,2017,August,35,31,2,5,3,...,0,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07
102891,City Hotel,0,34,2017,August,35,31,2,5,2,...,0,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07
102892,City Hotel,0,109,2017,August,35,31,2,5,2,...,0,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07
102893,City Hotel,0,205,2017,August,35,29,2,7,2,...,0,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102894 entries, 0 to 102893
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           102894 non-null  object
 1   is_canceled                     102894 non-null  int64
 2   lead_time                       102894 non-null  int64
 3   arrival_date_year               102894 non-null  int64
 4   arrival_date_month              102894 non-null  object
 5   arrival_date_week_number        102894 non-null  int64
 6   arrival_date_day_of_month       102894 non-null  int64
 7   stays_in_weekend_nights         102894 non-null  int64
 8   stays_in_week_nights            102894 non-null  int64
 9   adults                          102894 non-null  int64
 10  children                        102894 non-null  float64
 11  babies                          102894 non-null  int64
 12  meal                            102894 non-null  object
 13  country                         102894 non-null  object
 14  market_segment                  102894 non-null  object
 15  distribution_channel            102894 non-null  object
 16  is_repeated_guest               102894 non-null  int64
 17  previous_cancellations          102894 non-null  int64
 18  previous_bookings_not_canceled  102894 non-null  int64
 19  reserved_room_type              102894 non-null  object
 20  assigned_room_type              102894 non-null  object
 21  booking_changes                 102894 non-null  int64
 22  deposit_type                    102894 non-null  object
 23  agent                           102894 non-null  float64
 24  days_in_waiting_list            102894 non-null  int64
 25  customer_type                   102894 non-null  object
 26  adr                             102894 non-null  float64
 27  required_car_parking_spaces     102894 non-null  int64
 28  total_of_special_requests       102894 non-null  int64
 29  reservation_status              102894 non-null  object
 30  reservation_status_date         102894 non-null  object
dtypes: float64(3), int64(16), object(12)
memory usage: 24.3+ MB